### ISSUE TITLE
Does the fan function still works?

### ISSUE THREAD

**Issue by codychowjl** [MichaelKirsch/KintaroSnes#6]
I remembered it was hold reset button 1-3 seconds to turn on the fan. However I have done so and fan did not turn on despite going over >60 degree Celsius.

**Comment by MichaelKirsch** [comment]
yes this feature was deleted in the last revision. im sorry mate. i didnt want to support it anymore. you can manually change the script and set it there

**Comment by MichaelKirsch** [comment]
but i will look into it

**Comment by snock** [comment]
I just installed retropie 4.6, and installing the script gives me that error.

pi@retropie:~/develop/KintaroSnes $ sudo systemctl status kintaro
● kintaro.service - Kintaro PCB-Script
   Loaded: loaded (/etc/systemd/system/kintaro.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-05-03 01:52:33 BST; 1s ago
 Main PID: 5169 (pcb.py)
    Tasks: 2 (limit: 1772)
   Memory: 2.4M
   CGroup: /system.slice/kintaro.service
           └─5169 /usr/bin/python3 -u /opt/kintaro/pcb.py

May 03 01:52:33 retropie systemd[1]: Started Kintaro PCB-Script.
May 03 01:52:33 retropie kintaro[5169]: /opt/kintaro/pcb.py:29: RuntimeWarning: This channel is already in use, continui
May 03 01:52:33 retropie kintaro[5169]:   GPIO.setup(pcb_components["LED"], GPIO.OUT) #LED Output
May 03 01:52:33 retropie kintaro[5169]: /opt/kintaro/pcb.py:30: RuntimeWarning: This channel is ```
already in use, continui
May 03 01:52:33 retropie kintaro[5169]:   GPIO.setup(pcb_components["FAN"], GPIO.OUT) #FAN Output
May 03 01:52:33 retropie kintaro[5169]: /opt/kintaro/pcb.py:32: RuntimeWarning: A physical pull up resistor is fitted on
May 03 01:52:33 retropie kintaro[5169]:   GPIO.setup(pcb_components["RESET"], GPIO.IN, pull_up_down=GPIO.PUD_UP) #set pi

```

**Comment by MichaelKirsch** [comment]
yeah you need to reinstall all of it i think

**Comment by snock** [comment]
in the end it worked, thanks. I'm seeing how to control the speed of the
fans that is always the same.
